<?php

namespace Rotary\Grants\Support;

defined( 'ABSPATH' ) || exit;

/**
 * CSV output that is safe to open in a spreadsheet (docs/04).
 *
 * Text cells: anything that a spreadsheet could read as a formula — a cell
 * whose first non-whitespace character is = + - @, or that starts with a
 * tab or carriage return — is prefixed with an apostrophe. Money, date and
 * integer columns are generated by the plugin (never user text) and kept
 * typed and predictable: money as plain signed pounds "1234.56".
 */
final class Csv {

    public const TEXT  = 'text';
    public const MONEY = 'money';
    public const DATE  = 'date';
    public const INT   = 'int';

    public static function text( mixed $value ): string {
        $s = (string) $value;
        if ( preg_match( '/^[\t\r]/', $s ) || preg_match( '/^\s*[=+\-@]/u', $s ) ) {
            return "'" . $s;
        }
        return $s;
    }

    /** Pence → "1234.56" / "-200.00"; null → "" (unknown, never 0). */
    public static function money( ?int $pence ): string {
        if ( $pence === null ) {
            return '';
        }
        $abs = abs( $pence );
        return ( $pence < 0 ? '-' : '' ) . intdiv( $abs, 100 ) . '.' . str_pad( (string) ( $abs % 100 ), 2, '0', STR_PAD_LEFT );
    }

    /**
     * Build CSV text.
     *
     * @param array<string, array{0:string, 1:string}> $columns key => [header, type]
     * @param iterable<array<string,mixed>>            $rows
     */
    public static function build( array $columns, iterable $rows ): string {
        $fh = fopen( 'php://temp', 'w+' );
        fwrite( $fh, "\xEF\xBB\xBF" ); // UTF-8 BOM so Excel reads £ and accents correctly
        fputcsv( $fh, array_map( [ self::class, 'text' ], array_column( $columns, 0 ) ), ',', '"', '' );
        foreach ( $rows as $row ) {
            $line = [];
            foreach ( $columns as $key => [ , $type ] ) {
                $v      = $row[ $key ] ?? null;
                $line[] = match ( $type ) {
                    self::MONEY => self::money( $v === null || $v === '' ? null : (int) $v ),
                    self::INT   => $v === null || $v === '' ? '' : (string) (int) $v,
                    self::DATE  => preg_match( '/^\d{4}-\d{2}-\d{2}/', (string) $v ) ? substr( (string) $v, 0, 10 ) : '',
                    default     => self::text( $v ?? '' ),
                };
            }
            fputcsv( $fh, $line, ',', '"', '' );
        }
        rewind( $fh );
        $out = (string) stream_get_contents( $fh );
        fclose( $fh );
        return $out;
    }
}
